import { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'fr' | 'rw';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation and common
    'nav.home': 'Home',
    'nav.calendar': 'Calendar',
    'nav.camera': 'Camera',
    'nav.market': 'Market',
    'nav.tools': 'Tools',
    'nav.settings': 'Settings',
    'welcome.back': 'Welcome back',
    'farmer': 'Farmer',
    'loading': 'Loading...',
    
    // Tools page
    'tools.title': 'Farm Tools',
    'tools.subtitle': 'Access powerful tools to enhance your farming',
    'tools.smartInputPlanner': 'Smart Input Planner',
    'tools.cropTracker': 'Crop Tracker',
    'tools.farmingGame': 'Farming Game',
    'tools.podcast': 'Farm Podcast',
    'tools.marketplace': 'Smart Marketplace',
    'tools.challenges': 'Farm Challenges',
    'tools.learning': 'Learning Paths',
    'tools.mentorship': 'Mentorship',
    'tools.risk': 'Risk Dashboard',
    'tools.diversification': 'Crop Diversification',
    'tools.investment': 'Micro-Investment',
    'tools.mapping': 'Plot Mapping',
    'tools.mythbuster': 'Mythbuster',
    'tools.customTips': 'Custom Tips',
    'tools.expertFinder': 'Expert Finder',
    
    // Smart Input Planner
    'planner.title': 'Smart Input Planner',
    'planner.subtitle': 'Calculate the exact amount of inputs needed for your farm',
    'planner.landSize': 'Land Size (acres)',
    'planner.enterLandSize': 'Enter your land size',
    'planner.cropType': 'Crop Type',
    'planner.selectCrop': 'Select crop type',
    'planner.calculate': 'Calculate Inputs',
    'planner.recommendations': 'Recommended Inputs',
    'planner.seeds': 'Seeds',
    'planner.fertilizer': 'Fertilizer',
    'planner.pesticide': 'Pesticide',
    'planner.maize': 'Maize',
    'planner.beans': 'Beans',
    'planner.cassava': 'Cassava',
    'planner.rice': 'Rice',
    
    // Crop Tracker
    'tracker.title': 'AI Crop Growth Tracker',
    'tracker.subtitle': 'Track your crop\'s progress with AI-powered photo analysis',
    'tracker.currentCrop': 'Current Crop: Maize Field A',
    'tracker.takePhoto': 'Take Photo',
    'tracker.week': 'Week',
    'tracker.aiAnalysis': 'AI Analysis:',
    'tracker.yourNotes': 'Your Notes:',
    'tracker.actionRequired': 'Action Required',
    'tracker.progressSummary': 'Growth Progress Summary',
    'tracker.healthScore': 'Health Score',
    'tracker.photosTaken': 'Photos Taken',
    'tracker.daysTracked': 'Days Tracked',
    
    // Main page
    'main.welcome': 'Your intelligent farming companion is here to help',
    'main.tour': 'View App Tour',
    'main.overview': 'Farm Overview',
    'main.connected': 'Stay Connected',
    'main.tools': 'Farm Tools',
    'main.quickAnalysis': 'Quick Analysis',
    'main.achievements': 'Farming Achievements',
    'main.cropsMonitored': 'Crops Monitored',
    'main.yieldImproved': 'Yield Improved',
    'main.communityInsights': 'Community Insights',
    'main.quickActions': 'Quick Actions',
    'main.addTask': 'Add Task',
    'main.checkPrices': 'Check Prices',
    'main.recentAnalyses': 'Recent Analyses',
    'main.tomatoHealth': 'Tomato Plant Health',
    'main.beanAnalysis': 'Bean Leaf Analysis',
    'main.cassavaCheck': 'Cassava Growth Check',
    'main.healthy': 'Healthy',
    'main.attention': 'Attention',
    'main.excellent': 'Excellent',
    
    // Market
    'market.title': 'Market Prices',
    'market.subtitle': 'Real-time crop prices and market trends',
    'market.refresh': 'Refresh',
    'market.all': 'All Crops',
    'market.rising': 'Rising',
    'market.falling': 'Falling',
    'market.stable': 'Stable',
    'market.insights': 'Market Insights',
    'market.opportunities': 'Best Opportunities',
    'market.hold': 'Hold Recommendations',
    'market.trend': 'Market Trend',
    
    // Camera Analysis
    'camera.title': 'Crop Analysis',
    'camera.subtitle': 'Use AI to analyze your crops instantly',
    'camera.smartAnalysis': 'Smart Crop Analysis',
    'camera.launchReady': 'Launch Ready',
    'camera.health': 'Crop Health',
    'camera.pest': 'Pest Detection',
    'camera.disease': 'Disease Analysis',
    'camera.growth': 'Growth Tracking',
    'camera.take': 'Take Photo',
    'camera.select': 'Select from Gallery',
    'camera.analyzing': 'Analyzing crop with AI...',
    'camera.diagnosis': 'Disease Diagnosis',
    'camera.symptoms': 'Symptoms Detected:',
    'camera.causes': 'Possible Causes:',
    'camera.immediate': 'Immediate Actions Required',
    'camera.treatment': 'Treatment Plan',
    'camera.preventive': 'Preventive Measures',
    'camera.another': 'Analyze Another Photo',
    'camera.capture': 'Capture',
    'camera.report': 'Report',
    'camera.history': 'History',
    'camera.active': 'Active',
    'camera.premium': 'Premium',
    'camera.new': 'New',
    'camera.weatherConditions': 'Weather Conditions (Kigali)',
    'camera.temperature': 'Temperature',
    'camera.humidity': 'Humidity',
    'camera.windSpeed': 'Wind Speed',
    'camera.uvIndex': 'UV Index',
    'camera.moderate': 'Moderate',
    'camera.recommendedCrops': 'Recommended Local Crops',
    'camera.excellentSeason': 'Excellent season',
    'camera.goodToPlant': 'Good to plant',
    'camera.monitorWeather': 'Monitor weather',
    'camera.perfectConditions': 'Perfect conditions',
    
    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Customize your AgriTech Advisor experience',
    'settings.profile': 'Profile',
    'settings.farmLocation': 'Farm Location',
    'settings.currentLocation': 'Current Location',
    'settings.useGPS': 'Use Current GPS Location',
    'settings.unitsPreferences': 'Units & Preferences',
    'settings.temperatureUnits': 'Temperature Units',
    'settings.celsius': 'Celsius (°C)',
    'settings.fahrenheit': 'Fahrenheit (°F)',
    'settings.language': 'Language',
    'settings.notifications': 'Notifications & Alerts',
    'settings.pushNotifications': 'Push Notifications',
    'settings.weatherAlerts': 'Weather alerts and reminders',
    'settings.emailUpdates': 'Email Updates',
    'settings.weeklyReports': 'Weekly reports and tips',
    'settings.weatherAlertsDesc': 'Severe weather warnings',
    'settings.marketAlerts': 'Market Alerts',
    'settings.priceChanges': 'Price changes and trends',
    'settings.dataPrivacy': 'Data & Privacy',
    'settings.exportData': 'Export Your Data',
    'settings.downloadData': 'Download all your farm data',
    'settings.privacySettings': 'Privacy Settings',
    'settings.dataSharing': 'Control data sharing preferences',
    'settings.supportFeedback': 'Support & Feedback',
    'settings.getHelp': 'Get Help',
    'settings.shareApp': 'Share App',
    'settings.rateApp': 'Rate App',
    'settings.signOut': 'Sign Out',
    'settings.appInfo': 'AgriTech Advisor',
    'settings.version': 'Version 1.0.0 • Build 2024.1 • Rwanda Edition',
    'settings.premium': 'Premium',
    'settings.active': 'Active',
    'settings.memberSince': 'Member since Jan 2024',
    'settings.editProfile': 'Edit Profile',
    'settings.saveChanges': 'Save Changes',
    'settings.cancel': 'Cancel',
    'settings.defaultLocation': 'Default location set to Kigali, Rwanda',
    'settings.english': 'English',
    'settings.french': 'Français',
    'settings.kinyarwanda': 'Kinyarwanda',
    'settings.privacy': 'Privacy',
    
    // Notifications
    'notifications.profileUpdated': 'Profile Picture Updated',
    'notifications.profileUploaded': 'Your profile picture has been uploaded successfully.',
    'notifications.profileSaved': 'Profile Updated',
    'notifications.profileSavedDesc': 'Your profile information has been saved successfully.',
    'notifications.settingsUpdated': 'Settings Updated',
    'notifications.notificationsEnabled': 'notifications enabled',
    'notifications.notificationsDisabled': 'notifications disabled',
    'notifications.languageUpdated': 'Language Updated',
    'notifications.languageChanged': 'Language changed to',
    'notifications.dataExported': 'Data Exported',
    'notifications.dataDownloaded': 'Your farm data has been downloaded successfully.',
    'notifications.linkCopied': 'Link Copied',
    'notifications.linkCopiedDesc': 'App link copied to clipboard. Share it with other farmers!',
    'notifications.thankYou': 'Thank You!',
    'notifications.rateThankYou': 'Thank you for wanting to rate AgriTech Advisor. We appreciate your feedback!',
    
    // Community insights
    'community.cassavaReport': 'Local farmers report good cassava season',
    'community.rainAlert': 'Rain expected next week - prepare irrigation',
    'community.beanPrices': 'Bean prices up 15% in Kigali market',
    'community.hoursAgo': 'h ago',
    'community.dayAgo': 'd ago',
    
    // Time indicators
    'time.hoursAgo': 'hours ago',
    'time.dayAgo': 'day ago',
    'time.daysAgo': 'days ago',
  },
  fr: {
    // Navigation and common
    'nav.home': 'Accueil',
    'nav.calendar': 'Calendrier',
    'nav.camera': 'Caméra',
    'nav.market': 'Marché',
    'nav.tools': 'Outils',
    'nav.settings': 'Paramètres',
    'welcome.back': 'Bon retour',
    'farmer': 'Fermier',
    'loading': 'Chargement...',
    
    // Tools page
    'tools.title': 'Outils de Ferme',
    'tools.subtitle': 'Accédez à des outils puissants pour améliorer votre agriculture',
    'tools.smartInputPlanner': 'Planificateur d\'Intrants Intelligent',
    'tools.cropTracker': 'Suivi des Cultures',
    'tools.farmingGame': 'Jeu d\'Agriculture',
    'tools.podcast': 'Podcast de Ferme',
    'tools.marketplace': 'Marché Intelligent',
    'tools.challenges': 'Défis de Ferme',
    'tools.learning': 'Parcours d\'Apprentissage',
    'tools.mentorship': 'Mentorat',
    'tools.risk': 'Tableau de Bord des Risques',
    'tools.diversification': 'Diversification des Cultures',
    'tools.investment': 'Micro-Investissement',
    'tools.mapping': 'Cartographie des Parcelles',
    'tools.mythbuster': 'Démystificateur',
    'tools.customTips': 'Conseils Personnalisés',
    'tools.expertFinder': 'Chercheur d\'Experts',
    
    // Smart Input Planner
    'planner.title': 'Planificateur d\'Intrants Intelligent',
    'planner.subtitle': 'Calculez la quantité exacte d\'intrants nécessaires pour votre ferme',
    'planner.landSize': 'Taille du Terrain (acres)',
    'planner.enterLandSize': 'Entrez la taille de votre terrain',
    'planner.cropType': 'Type de Culture',
    'planner.selectCrop': 'Sélectionnez le type de culture',
    'planner.calculate': 'Calculer les Intrants',
    'planner.recommendations': 'Intrants Recommandés',
    'planner.seeds': 'Graines',
    'planner.fertilizer': 'Engrais',
    'planner.pesticide': 'Pesticide',
    'planner.maize': 'Maïs',
    'planner.beans': 'Haricots',
    'planner.cassava': 'Manioc',
    'planner.rice': 'Riz',
    
    // Crop Tracker
    'tracker.title': 'Suivi de Croissance des Cultures IA',
    'tracker.subtitle': 'Suivez les progrès de vos cultures avec l\'analyse photo alimentée par l\'IA',
    'tracker.currentCrop': 'Culture Actuelle: Champ de Maïs A',
    'tracker.takePhoto': 'Prendre une Photo',
    'tracker.week': 'Semaine',
    'tracker.aiAnalysis': 'Analyse IA:',
    'tracker.yourNotes': 'Vos Notes:',
    'tracker.actionRequired': 'Action Requise',
    'tracker.progressSummary': 'Résumé des Progrès de Croissance',
    'tracker.healthScore': 'Score de Santé',
    'tracker.photosTaken': 'Photos Prises',
    'tracker.daysTracked': 'Jours Suivis',
    
    // Main page
    'main.welcome': 'Votre compagnon agricole intelligent est là pour vous aider',
    'main.tour': 'Voir la Visite de l\'App',
    'main.overview': 'Aperçu de la Ferme',
    'main.connected': 'Restez Connecté',
    'main.tools': 'Outils de Ferme',
    'main.quickAnalysis': 'Analyse Rapide',
    'main.achievements': 'Réalisations Agricoles',
    'main.cropsMonitored': 'Cultures Surveillées',
    'main.yieldImproved': 'Rendement Amélioré',
    'main.communityInsights': 'Aperçus Communautaires',
    'main.quickActions': 'Actions Rapides',
    'main.addTask': 'Ajouter Tâche',
    'main.checkPrices': 'Vérifier Prix',
    'main.recentAnalyses': 'Analyses Récentes',
    'main.tomatoHealth': 'Santé des Plants de Tomate',
    'main.beanAnalysis': 'Analyse des Feuilles de Haricot',
    'main.cassavaCheck': 'Vérification Croissance Manioc',
    'main.healthy': 'Sain',
    'main.attention': 'Attention',
    'main.excellent': 'Excellent',
    
    // Market
    'market.title': 'Prix du Marché',
    'market.subtitle': 'Prix des cultures en temps réel et tendances du marché',
    'market.refresh': 'Actualiser',
    'market.all': 'Toutes les Cultures',
    'market.rising': 'En Hausse',
    'market.falling': 'En Baisse',
    'market.stable': 'Stable',
    'market.insights': 'Analyses du Marché',
    'market.opportunities': 'Meilleures Opportunités',
    'market.hold': 'Recommandations de Conservation',
    'market.trend': 'Tendance du Marché',
    
    // Camera Analysis
    'camera.title': 'Analyse des Cultures',
    'camera.subtitle': 'Utilisez l\'IA pour analyser vos cultures instantanément',
    'camera.smartAnalysis': 'Analyse Intelligente des Cultures',
    'camera.launchReady': 'Prêt au Lancement',
    'camera.health': 'Santé des Cultures',
    'camera.pest': 'Détection de Ravageurs',
    'camera.disease': 'Analyse de Maladies',
    'camera.growth': 'Suivi de Croissance',
    'camera.take': 'Prendre une Photo',
    'camera.select': 'Sélectionner de la Galerie',
    'camera.analyzing': 'Analyse des cultures avec AI...',
    'camera.diagnosis': 'Diagnostic de Maladie',
    'camera.symptoms': 'Symptômes Détectés:',
    'camera.causes': 'Causes Possibles:',
    'camera.immediate': 'Actions Immédiates Requises',
    'camera.treatment': 'Plan de Traitement',
    'camera.preventive': 'Mesures Préventives',
    'camera.another': 'Analyser une Autre Photo',
    'camera.capture': 'Capturer',
    'camera.report': 'Rapport',
    'camera.history': 'Historique',
    'camera.active': 'Actif',
    'camera.premium': 'Premium',
    'camera.new': 'Nouveau',
    'camera.weatherConditions': 'Conditions Météo (Kigali)',
    'camera.temperature': 'Température',
    'camera.humidity': 'Humidité',
    'camera.windSpeed': 'Vitesse du Vent',
    'camera.uvIndex': 'Indice UV',
    'camera.moderate': 'Modéré',
    'camera.recommendedCrops': 'Cultures Locales Recommandées',
    'camera.excellentSeason': 'Excellente saison',
    'camera.goodToPlant': 'Bon à planter',
    'camera.monitorWeather': 'Surveiller météo',
    'camera.perfectConditions': 'Conditions parfaites',
    
    // Settings
    'settings.title': 'Paramètres',
    'settings.subtitle': 'Personnalisez votre expérience AgriTech Advisor',
    'settings.profile': 'Profil',
    'settings.farmLocation': 'Emplacement de la Ferme',
    'settings.currentLocation': 'Emplacement Actuel',
    'settings.useGPS': 'Utiliser la Localisation GPS Actuelle',
    'settings.unitsPreferences': 'Unités et Préférences',
    'settings.temperatureUnits': 'Unités de Température',
    'settings.celsius': 'Celsius (°C)',
    'settings.fahrenheit': 'Fahrenheit (°F)',
    'settings.language': 'Langue',
    'settings.notifications': 'Notifications et Alertes',
    'settings.pushNotifications': 'Notifications Push',
    'settings.weatherAlerts': 'Alertes météo et rappels',
    'settings.emailUpdates': 'Mises à jour Email',
    'settings.weeklyReports': 'Rapports hebdomadaires et conseils',
    'settings.weatherAlertsDesc': 'Avertissements météo sévères',
    'settings.marketAlerts': 'Alertes de Marché',
    'settings.priceChanges': 'Changements de prix et tendances',
    'settings.dataPrivacy': 'Données et Confidentialité',
    'settings.exportData': 'Exporter Vos Données',
    'settings.downloadData': 'Télécharger toutes vos données de ferme',
    'settings.privacySettings': 'Paramètres de Confidentialité',
    'settings.dataSharing': 'Contrôler les préférences de partage de données',
    'settings.supportFeedback': 'Support et Commentaires',
    'settings.getHelp': 'Obtenir de l\'Aide',
    'settings.shareApp': 'Partager l\'App',
    'settings.rateApp': 'Évaluer l\'App',
    'settings.signOut': 'Se Déconnecter',
    'settings.appInfo': 'AgriTech Advisor',
    'settings.version': 'Version 1.0.0 • Build 2024.1 • Édition Rwanda',
    'settings.premium': 'Premium',
    'settings.active': 'Actif',
    'settings.memberSince': 'Membre depuis Jan 2024',
    'settings.editProfile': 'Modifier le Profil',
    'settings.saveChanges': 'Sauvegarder les Modifications',
    'settings.cancel': 'Annuler',
    'settings.defaultLocation': 'Emplacement par défaut défini à Kigali, Rwanda',
    'settings.english': 'English',
    'settings.french': 'Français',
    'settings.kinyarwanda': 'Kinyarwanda',
    'settings.privacy': 'Confidentialité',
    
    // Notifications
    'notifications.profileUpdated': 'Photo de Profil Mise à Jour',
    'notifications.profileUploaded': 'Votre photo de profil a été téléchargée avec succès.',
    'notifications.profileSaved': 'Profil Mis à Jour',
    'notifications.profileSavedDesc': 'Vos informations de profil ont été sauvegardées avec succès.',
    'notifications.settingsUpdated': 'Paramètres Mis à Jour',
    'notifications.notificationsEnabled': 'notifications activées',
    'notifications.notificationsDisabled': 'notifications désactivées',
    'notifications.languageUpdated': 'Langue Mise à Jour',
    'notifications.languageChanged': 'Langue changée vers',
    'notifications.dataExported': 'Données Exportées',
    'notifications.dataDownloaded': 'Vos données de ferme ont été téléchargées avec succès.',
    'notifications.linkCopied': 'Lien Copié',
    'notifications.linkCopiedDesc': 'Lien de l\'app copié dans le presse-papiers. Partagez-le avec d\'autres fermiers!',
    'notifications.thankYou': 'Merci!',
    'notifications.rateThankYou': 'Merci de vouloir évaluer AgriTech Advisor. Nous apprécions vos commentaires!',
    
    // Community insights
    'community.cassavaReport': 'Les fermiers locaux rapportent une bonne saison de manioc',
    'community.rainAlert': 'Pluie prévue la semaine prochaine - préparer irrigation',
    'community.beanPrices': 'Prix des haricots en hausse de 15% au marché de Kigali',
    'community.hoursAgo': 'h il y a',
    'community.dayAgo': 'j il y a',
    
    // Time indicators
    'time.hoursAgo': 'heures il y a',
    'time.dayAgo': 'jour il y a',
    'time.daysAgo': 'jours il y a',
  },
  rw: {
    // Navigation and common
    'nav.home': 'Urugo',
    'nav.calendar': 'Kalindari',
    'nav.camera': 'Kamera',
    'nav.market': 'Isoko',
    'nav.tools': 'Ibikoresho',
    'nav.settings': 'Igenamiterere',
    'welcome.back': 'Murakaza neza',
    'farmer': 'Umuhinzi',
    'loading': 'Birateguye...',
    
    // Tools page
    'tools.title': 'Ibikoresho by\'Umurima',
    'tools.subtitle': 'Koresha ibikoresho bikomeye kugira neza ubuhinzi bwawe',
    'tools.smartInputPlanner': 'Igenamiterere ry\'Ibinyuranye Ryubwenge',
    'tools.cropTracker': 'Gukurikirana Ibihingwa',
    'tools.farmingGame': 'Umukino w\'Ubuhinzi',
    'tools.podcast': 'Podcast y\'Umurima',
    'tools.marketplace': 'Isoko Ryubwenge',
    'tools.challenges': 'Ibibazo by\'Umurima',
    'tools.learning': 'Inzira z\'Kwiga',
    'tools.mentorship': 'Ubuyobozi',
    'tools.risk': 'Ibikurura by\'Ibyago',
    'tools.diversification': 'Gutandukanya Ibihingwa',
    'tools.investment': 'Ishoramari Rito',
    'tools.mapping': 'Gushushanya Imirima',
    'tools.mythbuster': 'Kuraguza Amahano',
    'tools.customTips': 'Inama Zihariye',
    'tools.expertFinder': 'Gushakisha Impuguke',
    
    // Smart Input Planner
    'planner.title': 'Igenamiterere ry\'Ibinyuranye Ryubwenge',
    'planner.subtitle': 'Kubara umubare nyayo w\'ibinyuranye bikenewe ku murima wawe',
    'planner.landSize': 'Ubunini bw\'Ubutaka (acres)',
    'planner.enterLandSize': 'Shyiramo ubunini bw\'ubutaka bwawe',
    'planner.cropType': 'Ubwoko bw\'Igihingwa',
    'planner.selectCrop': 'Hitamo ubwoko bw\'igihingwa',
    'planner.calculate': 'Kubara Ibinyuranye',
    'planner.recommendations': 'Ibinyuranye Bisabwa',
    'planner.seeds': 'Imbuto',
    'planner.fertilizer': 'Ifumbire',
    'planner.pesticide': 'Imiti y\'Udukoko',
    'planner.maize': 'Ibigori',
    'planner.beans': 'Ibishyimbo',
    'planner.cassava': 'Amaru',
    'planner.rice': 'Umuceri',
    
    // Crop Tracker
    'tracker.title': 'Gukurikirana Imikurire y\'Ibihingwa na AI',
    'tracker.subtitle': 'Kurikirana uko ibihingwa byawe bigenda bishingiye ku isesengura ry\'amafoto rifashijwe na AI',
    'tracker.currentCrop': 'Igihingwa cy\'Ubu: Umurima w\'Ibigori A',
    'tracker.takePhoto': 'Fata Ishusho',
    'tracker.week': 'Icyumweru',
    'tracker.aiAnalysis': 'Isesengura rya AI:',
    'tracker.yourNotes': 'Inyandiko Zawe:',
    'tracker.actionRequired': 'Igikorwa Gikenewe',
    'tracker.progressSummary': 'Incamake y\'Iterambere',
    'tracker.healthScore': 'Amanota y\'Ubuzima',
    'tracker.photosTaken': 'Amafoto Yafashwe',
    'tracker.daysTracked': 'Iminsi Yakurikiranijwe',
    
    // Main page
    'main.welcome': 'Umunyangazi wawe w\'ubuhinzi buteganyirije kugufasha',
    'main.tour': 'Reba Uruzinduko rw\'Porogaramu',
    'main.overview': 'Isanzure ry\'Umurima',
    'main.connected': 'Komeza Uhuye',
    'main.tools': 'Ibikoresho by\'Umurima',
    'main.quickAnalysis': 'Isesengura Ryihuse',
    'main.achievements': 'Intsinzi z\'Ubuhinzi',
    'main.cropsMonitored': 'Ibihingwa Bikurikiranwa',
    'main.yieldImproved': 'Umusaruro Wiyongereye',
    'main.communityInsights': 'Ubumenyi bw\'Abaturage',
    'main.quickActions': 'Ibikorwa Byihuse',
    'main.addTask': 'Ongeraho Umurimo',
    'main.checkPrices': 'Reba Ibiciro',
    'main.recentAnalyses': 'Isesengura Riheruka',
    'main.tomatoHealth': 'Ubuzima bw\'Inyanya',
    'main.beanAnalysis': 'Isesengura ry\'Amababi y\'Ibishyimbo',
    'main.cassavaCheck': 'Gusuzuma Imikurire y\'Amaru',
    'main.healthy': 'Mwiza',
    'main.attention': 'Witondere',
    'main.excellent': 'Biryoshye',
    
    // Market
    'market.title': 'Ibiciro by\'Isoko',
    'market.subtitle': 'Ibiciro by\'ibihingwa by\'igihe n\'icyerekezo cy\'isoko',
    'market.refresh': 'Vugurura',
    'market.all': 'Ibihingwa Byose',
    'market.rising': 'Bizamuka',
    'market.falling': 'Bigabanuka',
    'market.stable': 'Bihagaritse',
    'market.insights': 'Ubumenyi bw\'Isoko',
    'market.opportunities': 'Amahirwe Meza',
    'market.hold': 'Ibyifuzo byo Kugumya',
    'market.trend': 'Icyerekezo cy\'Isoko',
    
    // Camera Analysis
    'camera.title': 'Isesengura ry\'Ibihingwa',
    'camera.subtitle': 'Koresha AI kugira usesengure ibihingwa byawe ako kanya',
    'camera.smartAnalysis': 'Isesengura Ryubwenge ry\'Ibihingwa',
    'camera.launchReady': 'Biteguye Gutangizwa',
    'camera.health': 'Ubuzima bw\'Ibihingwa',
    'camera.pest': 'Gushakisha Udukoko',
    'camera.disease': 'Isesengura ry\'Indwara',
    'camera.growth': 'Gukurikirana Imikurire',
    'camera.take': 'Fata Ishusho',
    'camera.select': 'Hitamo mu Bubiko',
    'camera.analyzing': 'Gusesengura ibihingwa hamwe na AI...',
    'camera.diagnosis': 'Isesengura ry\'Indwara',
    'camera.symptoms': 'Ibimenyetso Byagaragaye:',
    'camera.causes': 'Intandaro Zishoboka:',
    'camera.immediate': 'Ibikorwa Byihutirwa Bikenewe',
    'camera.treatment': 'Gahunda y\'Ubuvuzi',
    'camera.preventive': 'Ingamba zo Kwirinda',
    'camera.another': 'Sesengura Indi Shusho',
    'camera.capture': 'Fata',
    'camera.report': 'Raporo',
    'camera.history': 'Amateka',
    'camera.active': 'Bikorwa',
    'camera.premium': 'Premium',
    'camera.new': 'Gishya',
    'camera.weatherConditions': 'Ibihe (Kigali)',
    'camera.temperature': 'Ubushyuhe',
    'camera.humidity': 'Ubushuhe',
    'camera.windSpeed': 'Umuvuduko w\'Umuyaga',
    'camera.uvIndex': 'Indangagaciro ya UV',
    'camera.moderate': 'Byoroshye',
    'camera.recommendedCrops': 'Ibihingwa by\'Aho Bisabwa',
    'camera.excellentSeason': 'Igihe kiryoshye',
    'camera.goodToPlant': 'Byiza guhinga',
    'camera.monitorWeather': 'Kurikirana ibihe',
    'camera.perfectConditions': 'Ibintu byuzuye',
    
    // Settings
    'settings.title': 'Igenamiterere',
    'settings.subtitle': 'Hindura uburyo bwawe bwo gukoresha AgriTech Advisor',
    'settings.profile': 'Umwirondoro',
    'settings.farmLocation': 'Aho Umurima uherereye',
    'settings.currentLocation': 'Aho Uherereye Ubu',
    'settings.useGPS': 'Koresha Aho Uherereye na GPS',
    'settings.unitsPreferences': 'Ingamba n\'Ibyifuzo',
    'settings.temperatureUnits': 'Ingamba z\'Ubushyuhe',
    'settings.celsius': 'Celsius (°C)',
    'settings.fahrenheit': 'Fahrenheit (°F)',
    'settings.language': 'Ururimi',
    'settings.notifications': 'Itumanaho n\'Iburira',
    'settings.pushNotifications': 'Itumanaho Risunzwa',
    'settings.weatherAlerts': 'Iburira ry\'ibihe n\'ibirikumbuza',
    'settings.emailUpdates': 'Amakuru ya Email',
    'settings.weeklyReports': 'Raporo z\'icyumweru n\'inama',
    'settings.weatherAlertsDesc': 'Iburira ry\'ibihe bikomeye',
    'settings.marketAlerts': 'Iburira ry\'Isoko',
    'settings.priceChanges': 'Guhinduka kw\'ibiciro n\'icyerekezo',
    'settings.dataPrivacy': 'Amakuru n\'Ibanga',
    'settings.exportData': 'Sohora Amakuru Yawe',
    'settings.downloadData': 'Kuramo amakuru yose y\'umurima wawe',
    'settings.privacySettings': 'Igenamiterere ry\'Ibanga',
    'settings.dataSharing': 'Kugenzura ibyifuzo byo gusangira amakuru',
    'settings.supportFeedback': 'Ubufasha n\'Ibitekerezo',
    'settings.getHelp': 'Bonera Ubufasha',
    'settings.shareApp': 'Sangira Porogaramu',
    'settings.rateApp': 'Tanga Amanota ku Porogaramu',
    'settings.signOut': 'Sohoka',
    'settings.appInfo': 'AgriTech Advisor',
    'settings.version': 'Verisiyo 1.0.0 • Build 2024.1 • Verisiyo ya Rwanda',
    'settings.premium': 'Premium',
    'settings.active': 'Irakora',
    'settings.memberSince': 'Umunyamuryango kuva Mut 2024',
    'settings.editProfile': 'Hindura Umwirondoro',
    'settings.saveChanges': 'Bika Impinduka',
    'settings.cancel': 'Bireke',
    'settings.defaultLocation': 'Aho uherereye mburabuzi ni Kigali, Rwanda',
    'settings.english': 'Icyongereza',
    'settings.french': 'Igifaransa',
    'settings.kinyarwanda': 'Ikinyarwanda',
    'settings.privacy': 'Ibanga',
    
    // Notifications
    'notifications.profileUpdated': 'Ishusho y\'Umwirondoro Yavuguruwe',
    'notifications.profileUploaded': 'Ishusho y\'umwirondoro yawe yoherejwe neza.',
    'notifications.profileSaved': 'Umwirondoro Wavuguruwe',
    'notifications.profileSavedDesc': 'Amakuru y\'umwirondoro yawe yabitswe neza.',
    'notifications.settingsUpdated': 'Igenamiterere Ryavuguruwe',
    'notifications.notificationsEnabled': 'itumanaho rirakora',
    'notifications.notificationsDisabled': 'itumanaho rirazimye',
    'notifications.languageUpdated': 'Ururimi Rwavuguruwe',
    'notifications.languageChanged': 'Ururimi rwahinduwe ruri',
    'notifications.dataExported': 'Amakuru Yashyizwe Hanze',
    'notifications.dataDownloaded': 'Amakuru y\'umurima wawe yarajwe neza.',
    'notifications.linkCopied': 'Ihuza Ryakopijwe',
    'notifications.linkCopiedDesc': 'Ihuza ry\'porogaramu ryakopijwe. Sangira na bamwe bahinzi!',
    'notifications.thankYou': 'Murakoze!',
    'notifications.rateThankYou': 'Murakoze gushaka gutanga amanota kuri AgriTech Advisor. Tushimira ibitekerezo byanyu!',
    
    // Community insights
    'community.cassavaReport': 'Abahinzi bo hafi bavuga ko igihe cy\'amaru ari cyiza',
    'community.rainAlert': 'Imvura iteganijwe mu cyumweru gitaha - tegura ubuhira',
    'community.beanPrices': 'Ibiciro by\'ibishyimbo byiyongereye 15% ku isoko rya Kigali',
    'community.hoursAgo': 'sh shize',
    'community.dayAgo': 'uw ushize',
    
    // Time indicators
    'time.hoursAgo': 'amasaha ashize',
    'time.dayAgo': 'umunsi ushize',
    'time.daysAgo': 'iminsi ishize',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
