// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eskoygzvphbagpgzutxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVza295Z3p2cGhiYWdwZ3p1dHhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTg4NjIsImV4cCI6MjA2Mzc3NDg2Mn0.CGdjNotM4ML3D6J0TGbkR_DxKCZvJ-5GbjkD8foh-68";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);